# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    http_client:
        scoped_clients:
            news_api.client:
                base_uri: '%env(NEWS_API_BASE_URL)%'
                timeout: 5
                max_duration: 8
                retry_failed: false

    # Note that the session will be started ONLY if you read or write from it.
    session: true
    form: true
    property_access: true

    #esi: true
    #fragments: true

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
