<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260416173000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create news domain schema with users, articles, taxonomy, media and revisions';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('DROP TABLE IF EXISTS article CASCADE');

        $this->addSql('CREATE TABLE users (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, first_name VARCHAR(100) DEFAULT NULL, last_name VARCHAR(100) DEFAULT NULL, display_name VARCHAR(150) NOT NULL, is_active BOOLEAN DEFAULT TRUE NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_users_email ON users (email)');

        $this->addSql('CREATE TABLE categories (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, parent_id INT DEFAULT NULL, name VARCHAR(120) NOT NULL, slug VARCHAR(140) NOT NULL, description TEXT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_3AF34668727ACA70 ON categories (parent_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_categories_slug ON categories (slug)');

        $this->addSql('CREATE TABLE tags (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(80) NOT NULL, slug VARCHAR(120) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_tags_slug ON tags (slug)');

        $this->addSql('CREATE TABLE media (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, uploaded_by_id INT DEFAULT NULL, type VARCHAR(32) NOT NULL, path VARCHAR(1024) NOT NULL, mime_type VARCHAR(255) DEFAULT NULL, size_bytes INT DEFAULT NULL, alt_text VARCHAR(255) DEFAULT NULL, caption TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_6A2CA10C5B4B664D ON media (uploaded_by_id)');

        $this->addSql('CREATE TABLE articles (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, author_id INT NOT NULL, featured_image_id INT DEFAULT NULL, title VARCHAR(255) NOT NULL, slug VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, content TEXT NOT NULL, status VARCHAR(20) NOT NULL, published_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, is_breaking BOOLEAN DEFAULT FALSE NOT NULL, view_count INT DEFAULT 0 NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_BFDD3168F675F31B ON articles (author_id)');
        $this->addSql('CREATE INDEX IDX_BFDD3168DBB4D5E2 ON articles (featured_image_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_articles_slug ON articles (slug)');

        $this->addSql('CREATE TABLE article_categories (article_id INT NOT NULL, category_id INT NOT NULL, PRIMARY KEY(article_id, category_id))');
        $this->addSql('CREATE INDEX IDX_5EB73560FBE599C6 ON article_categories (article_id)');
        $this->addSql('CREATE INDEX IDX_5EB7356012469DE2 ON article_categories (category_id)');

        $this->addSql('CREATE TABLE article_tags (article_id INT NOT NULL, tag_id INT NOT NULL, PRIMARY KEY(article_id, tag_id))');
        $this->addSql('CREATE INDEX IDX_91969434FBE599C6 ON article_tags (article_id)');
        $this->addSql('CREATE INDEX IDX_91969434BAD26311 ON article_tags (tag_id)');

        $this->addSql('CREATE TABLE article_revisions (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, article_id INT NOT NULL, changed_by_id INT NOT NULL, title VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, content TEXT NOT NULL, change_note VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_5C7A057DFBE599C6 ON article_revisions (article_id)');
        $this->addSql('CREATE INDEX IDX_5C7A057D62F40B8F ON article_revisions (changed_by_id)');

        $this->addSql('ALTER TABLE categories ADD CONSTRAINT FK_3AF34668727ACA70 FOREIGN KEY (parent_id) REFERENCES categories (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE media ADD CONSTRAINT FK_6A2CA10C5B4B664D FOREIGN KEY (uploaded_by_id) REFERENCES users (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE articles ADD CONSTRAINT FK_BFDD3168F675F31B FOREIGN KEY (author_id) REFERENCES users (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE articles ADD CONSTRAINT FK_BFDD3168DBB4D5E2 FOREIGN KEY (featured_image_id) REFERENCES media (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE article_categories ADD CONSTRAINT FK_5EB73560FBE599C6 FOREIGN KEY (article_id) REFERENCES articles (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE article_categories ADD CONSTRAINT FK_5EB7356012469DE2 FOREIGN KEY (category_id) REFERENCES categories (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE article_tags ADD CONSTRAINT FK_91969434FBE599C6 FOREIGN KEY (article_id) REFERENCES articles (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE article_tags ADD CONSTRAINT FK_91969434BAD26311 FOREIGN KEY (tag_id) REFERENCES tags (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE article_revisions ADD CONSTRAINT FK_5C7A057DFBE599C6 FOREIGN KEY (article_id) REFERENCES articles (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE article_revisions ADD CONSTRAINT FK_5C7A057D62F40B8F FOREIGN KEY (changed_by_id) REFERENCES users (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE article_revisions DROP CONSTRAINT FK_5C7A057DFBE599C6');
        $this->addSql('ALTER TABLE article_revisions DROP CONSTRAINT FK_5C7A057D62F40B8F');
        $this->addSql('ALTER TABLE article_tags DROP CONSTRAINT FK_91969434FBE599C6');
        $this->addSql('ALTER TABLE article_tags DROP CONSTRAINT FK_91969434BAD26311');
        $this->addSql('ALTER TABLE article_categories DROP CONSTRAINT FK_5EB73560FBE599C6');
        $this->addSql('ALTER TABLE article_categories DROP CONSTRAINT FK_5EB7356012469DE2');
        $this->addSql('ALTER TABLE articles DROP CONSTRAINT FK_BFDD3168F675F31B');
        $this->addSql('ALTER TABLE articles DROP CONSTRAINT FK_BFDD3168DBB4D5E2');
        $this->addSql('ALTER TABLE media DROP CONSTRAINT FK_6A2CA10C5B4B664D');
        $this->addSql('ALTER TABLE categories DROP CONSTRAINT FK_3AF34668727ACA70');

        $this->addSql('DROP TABLE article_revisions');
        $this->addSql('DROP TABLE article_tags');
        $this->addSql('DROP TABLE article_categories');
        $this->addSql('DROP TABLE articles');
        $this->addSql('DROP TABLE media');
        $this->addSql('DROP TABLE tags');
        $this->addSql('DROP TABLE categories');
        $this->addSql('DROP TABLE users');

        $this->addSql('CREATE TABLE article (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, lead VARCHAR(500) DEFAULT NULL, content TEXT NOT NULL, published_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
    }
}
